export const USER_AUTH = "USER_AUTH";
export const USER_NOT_AUTH = "USER_NOT_AUTH";
export const CURRENT_USER_ANONYMOUS = "USER_ANONYMOUS";
export const CURRENT_USER_NOT_ANONYMOUS = "USER_NOT_ANONYMOUS";
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';